//! # Tachograph Gen1 Data Structures
//!
//! This module contains the specific data structures and parsing logic
//! for the first generation (Gen1) of digital tachograph data.

mod card_data;
mod card_response_data_parameter;
mod card_vehicle_record;
mod certificate;
mod company_card;
mod control_card;
mod driver_card;
mod driver_card_application_identification;
mod place_record;
mod previous_vehicle_info;
mod sensor_paired;
mod software_identification;
mod specific_conditions;
mod vu_activity;
mod vu_activity_daily_data;
mod vu_calibration_data;
mod vu_card_iw_data;
mod vu_company_locks_data;
mod vu_control_activity;
mod vu_data;
mod vu_detailed_speed;
mod vu_detailed_speed_data;
mod vu_download_activity_data;
mod vu_downloadable_period;
mod vu_event_data;
mod vu_events;
mod vu_fault_data;
mod vu_identification;
mod vu_over_speeding_event_data;
mod vu_overview;
mod vu_place_daily_work_period_data;
mod vu_specific_condition_data;
mod vu_technical_data;
mod vu_time_adjustment_data;
mod vu_transfer_response_parameter_data;
mod workshop_card;
mod workshop_card_application_identification;
mod workshop_card_calibration_record;

pub use card_data::CardData;
pub use card_response_data_parameter::CardResponseParameterData;
pub use card_vehicle_record::CardVehicleRecord;
pub use certificate::Certificate;
pub use company_card::CompanyCard;
pub use control_card::ControlCard;
pub use driver_card::DriverCard;
pub use driver_card_application_identification::DriverCardApplicationIdentification;
pub use place_record::PlaceRecord;
pub use previous_vehicle_info::PreviousVehicleInfo;
pub use sensor_paired::SensorPaired;
pub use software_identification::SoftwareIdentification;
pub use specific_conditions::{SpecificConditions, SpecificConditionsParams};
pub use vu_activity::VUActivity;
pub use vu_activity_daily_data::VuActivityDailyData;
pub use vu_calibration_data::VUCalibrationData;
pub use vu_card_iw_data::{VuCardIWData, VuCardIWRecord};
pub use vu_company_locks_data::{VuCompanyLocksData, VuCompanyLocksRecord};
pub use vu_control_activity::VuControlActivity;
pub use vu_data::VUData;
pub use vu_detailed_speed::VuDetailedSpeed;
pub use vu_detailed_speed_data::VuDetailedSpeedData;
pub use vu_download_activity_data::VuDownloadActivityData;
pub use vu_downloadable_period::VuDownloadablePeriod;
pub use vu_event_data::{VuEventData, VuEventRecord};
pub use vu_events::VuEvents;
pub use vu_fault_data::{VuFaultData, VuFaultRecord};
pub use vu_identification::VUIdentification;
pub use vu_over_speeding_event_data::{VuOverSpeedingEventData, VuOverSpeedingEventRecord};
pub use vu_overview::VuOverview;
pub use vu_place_daily_work_period_data::{VuPlaceDailyWorkPeriodData, VuPlaceDailyWorkPeriodRecord};
pub use vu_specific_condition_data::VuSpecificConditionData;
pub use vu_technical_data::VuTechnicalData;
pub use vu_time_adjustment_data::{VuTimeAdjustmentData, VuTimeAdjustmentRecord};
pub use vu_transfer_response_parameter_data::VUTransferResponseParameterData;
pub use workshop_card::WorkshopCard;
pub use workshop_card_application_identification::WorkshopCardApplicationIdentification;
pub use workshop_card_calibration_record::WorkshopCardCalibrationRecord;
