use crate::impl_enum_from_u8;

#[derive(Debug, PartialEq)]
#[repr(u8)]
pub enum EventFaultType {
    NoFurtherDetails = 0,
    InsertionOfNonValidCard = 1,
    CardConflict = 2,
    TimeOverlap = 3,
    DrivingWithoutAppropriateCard = 4,
    CardInsertionWhileDriving = 5,
    LastCardSessionNotCorrectlyClosed = 6,
    OverSpeeding = 7,
    PowerSupplyInterruption = 8,
    MotionDataError = 9,
    VehicleMotionConflict = 10,
    TimeConflict = 11,
    VuNoFurtherDetails = 16,
    VuMotionSensorAuthenticationFailure = 17,
    VuTachographCardAuthenticationFailure = 18,
    VuUnauthorisedChangeOfMotionSensor = 19,
    VuCardDataInputIntegrityError = 20,
    VuStoredUserDataIntegrityError = 21,
    VuInternalDataTransferError = 22,
    VuUnauthorisedCaseOpening = 23,
    VuHardwareSabotage = 24,
    SensorNoFurtherDetails = 32,
    SensorAuthenticationFailure = 33,
    SensorStoredDataIntegrityError = 34,
    SensorInternalDataTransferError = 35,
    SensorUnauthorisedCaseOpening = 36,
    SensorHardwareSabotage = 37,
    RENoFurtherDetails = 48,
    REVUInternalFault = 49,
    REPrinterFault = 50,
    REDisplayFault = 51,
    REDownloadingFault = 52,
    RESensorFault = 53,
    CardNoFurtherDetails = 64,
    GNSSNofurtherDetails = 80,
    GNSSInternalGNSSReceiverFault = 81,
    GNSSExternalGNSSReceiverFault = 82,
    GNSSExternalGNSSCommunicationFault = 83,
    GNSSNoGNSSPositionData = 84,
    GNSSTamperDetectionOfGNSS = 85,
    GNSSExternalGNSSFacilityCertificateExpired = 86,
    RCMNoFurtherDetails = 96,
    RCMRemoteCommunicationModuleFault = 97,
    RCMRemoteCommunicationModuleCommunicationFault = 98,
    ITSNoFurtherDetails = 112,
    Unknown = 255,
}

impl_enum_from_u8!(
    EventFaultType {
        NoFurtherDetails = 0,
        InsertionOfNonValidCard = 1,
        CardConflict = 2,
        TimeOverlap = 3,
        DrivingWithoutAppropriateCard = 4,
        CardInsertionWhileDriving = 5,
        LastCardSessionNotCorrectlyClosed = 6,
        OverSpeeding = 7,
        PowerSupplyInterruption = 8,
        MotionDataError = 9,
        VehicleMotionConflict = 10,
        TimeConflict = 11,
        VuNoFurtherDetails = 16,
        VuMotionSensorAuthenticationFailure = 17,
        VuTachographCardAuthenticationFailure = 18,
        VuUnauthorisedChangeOfMotionSensor = 19,
        VuCardDataInputIntegrityError = 20,
        VuStoredUserDataIntegrityError = 21,
        VuInternalDataTransferError = 22,
        VuUnauthorisedCaseOpening = 23,
        VuHardwareSabotage = 24,
        SensorNoFurtherDetails = 32,
        SensorAuthenticationFailure = 33,
        SensorStoredDataIntegrityError = 34,
        SensorInternalDataTransferError = 35,
        SensorUnauthorisedCaseOpening = 36,
        SensorHardwareSabotage = 37,
        RENoFurtherDetails = 48,
        REVUInternalFault = 49,
        REPrinterFault = 50,
        REDisplayFault = 51,
        REDownloadingFault = 52,
        RESensorFault = 53,
        CardNoFurtherDetails = 64,
        GNSSNofurtherDetails = 80,
        GNSSInternalGNSSReceiverFault = 81,
        GNSSExternalGNSSReceiverFault = 82,
        GNSSExternalGNSSCommunicationFault = 83,
        GNSSNoGNSSPositionData = 84,
        GNSSTamperDetectionOfGNSS = 85,
        GNSSExternalGNSSFacilityCertificateExpired = 86,
        RCMNoFurtherDetails = 96,
        RCMRemoteCommunicationModuleFault = 97,
        RCMRemoteCommunicationModuleCommunicationFault = 98,
        ITSNoFurtherDetails = 112,
        Unknown = 255
    }
);
