use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write;

use ts_rs::{Config, TS, TypeVisitor};

use crate::WasmTachographData;
use crate::gen2::{LoadType, OperationType};
use crate::tacho::{
    ActivityCard, ActivitySource, ActivityType, CalibrationPurpose, CardSlotNumber, CardStatus, ControlType, DrivingStatus,
    EntryTypeDailyWorkPeriod, EquipmentType, EventFaultRecordPurpose, EventFaultType, RegionNumeric, SpecificConditionType,
    VerifyResult,
};

struct DeclarationCollector<'a> {
    config: &'a Config,
    declarations: BTreeMap<String, String>,
    visited: HashSet<TypeId>,
}

impl<'a> DeclarationCollector<'a> {
    fn new(config: &'a Config) -> Self {
        Self { config, declarations: BTreeMap::new(), visited: HashSet::new() }
    }

    fn collect<T: TS + 'static>(&mut self) {
        self.visit::<T>();
    }
}

impl TypeVisitor for DeclarationCollector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.visited.insert(TypeId::of::<T>()) {
            return;
        }

        if T::output_path().is_some() {
            let identifier = T::ident(self.config);
            let declaration =
                format!("export {}", T::decl(self.config)).lines().map(str::trim_end).collect::<Vec<_>>().join("\n");
            if let Some(existing) = self.declarations.insert(identifier.clone(), declaration.clone()) {
                assert_eq!(existing, declaration, "conflicting TypeScript declarations for {identifier}");
            }
        }

        T::visit_dependencies(self);
    }
}

pub fn wasm_boundary_declaration() -> String {
    let config = Config::default();
    let mut collector = DeclarationCollector::new(&config);
    collector.collect::<ActivityCard>();
    collector.collect::<ActivitySource>();
    collector.collect::<ActivityType>();
    collector.collect::<CalibrationPurpose>();
    collector.collect::<CardSlotNumber>();
    collector.collect::<CardStatus>();
    collector.collect::<ControlType>();
    collector.collect::<DrivingStatus>();
    collector.collect::<EntryTypeDailyWorkPeriod>();
    collector.collect::<EquipmentType>();
    collector.collect::<EventFaultRecordPurpose>();
    collector.collect::<EventFaultType>();
    collector.collect::<LoadType>();
    collector.collect::<OperationType>();
    collector.collect::<RegionNumeric>();
    collector.collect::<SpecificConditionType>();
    collector.collect::<WasmTachographData>();
    collector.collect::<VerifyResult>();

    let mut output = String::from(
        "// This file is generated by `cargo run --features typescript --bin generate-types`.\n\
         // Do not edit it manually.\n\n",
    );

    for declaration in collector.declarations.values() {
        writeln!(output, "{declaration}\n").expect("writing to a String cannot fail");
    }

    output.push_str(
        "export type SupportedNationAlphaCodes = Readonly<Record<string, string>>;\n\n\
         export function getSupportedNationAlphaCodes(): SupportedNationAlphaCodes;\n\
         export function parse_from_memory(esmData: Uint8Array): WasmTachographData;\n\
         export function verify_card(\n\
             generation: CardGeneration,\n\
             dataFilesMap: unknown,\n\
             ercaPublicKey: Uint8Array,\n\
         ): VerifyResult;\n",
    );

    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_wasm_boundary_is_current() {
        assert_eq!(wasm_boundary_declaration(), include_str!("../types/wasm-boundary.d.ts"));
    }
}
